Homework02
Alisa-Mikulina/cs102B pull request #14
Opened 2021-11-16 21:01 UTC by Alisa-Mikulina

2021-12-30 14:37 UTC, anastasiiaCher requested changes

2021-12-30 14:37 UTC, anastasiiaCher commented on homework02/sudoku.py
> +        column.append(grid[i][pos[1]])
решите списковым включением

2021-12-30 14:37 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return block
эта задача решается одним коротеньким списковым включением (вся лаба про списковые включения)

2021-12-30 14:37 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    if possible_values == {}:
лучше `if not possible_values:`

2022-01-06 16:10 UTC, Alisa-Mikulina commented on homework02/sudoku.py
> +        column.append(grid[i][pos[1]])
Пушила с форсом, поэтому сюда оно, видимо, не высветилось. В коде все изменила.

2022-01-06 16:10 UTC, Alisa-Mikulina commented on homework02/sudoku.py
> +    return block
Пушила с форсом, поэтому сюда оно, видимо, не высветилось. В коде все изменила.

2022-01-06 16:10 UTC, Alisa-Mikulina commented on homework02/sudoku.py
> +    if possible_values == {}:
Пушила с форсом, поэтому сюда оно, видимо, не высветилось. В коде все изменила.

2022-01-17 05:24 UTC, anastasiiaCher approved these changes

2022-01-17 06:31 UTC, merged